version: "3.8"

services:
  web:
      build: ./services/web
      command: python manage.py run -h 0.0.0.0
      volumes:
          - ./services/web/:/usr/src/app/
      ports:
          - 5000:5000
      restart: always
      env_file:
          - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db_films
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432

volumes:
  postgres_data:
